#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace КП
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="pleshkova")]
	public partial class SorevnovaniyaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Определения метода расширяемости
    partial void OnCreated();
    partial void InsertSorevnovaniya(Sorevnovaniya instance);
    partial void UpdateSorevnovaniya(Sorevnovaniya instance);
    partial void DeleteSorevnovaniya(Sorevnovaniya instance);
    #endregion
		
		public SorevnovaniyaDataContext() : 
				base(global::КП.Properties.Settings.Default.DbConnect, mappingSource)
		{
			OnCreated();
		}
		
		public SorevnovaniyaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SorevnovaniyaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SorevnovaniyaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SorevnovaniyaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Sorevnovaniya> Sorevnovaniya
		{
			get
			{
				return this.GetTable<Sorevnovaniya>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Sorevnovaniya")]
	public partial class Sorevnovaniya : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_соревнования;
		
		private string _Название;
		
		private System.Nullable<System.DateTime> _Дата_проведения;
		
		private System.Nullable<int> _Максимальное_количество_участников;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_соревнованияChanging(int value);
    partial void OnID_соревнованияChanged();
    partial void OnНазваниеChanging(string value);
    partial void OnНазваниеChanged();
    partial void OnДата_проведенияChanging(System.Nullable<System.DateTime> value);
    partial void OnДата_проведенияChanged();
    partial void OnМаксимальное_количество_участниковChanging(System.Nullable<int> value);
    partial void OnМаксимальное_количество_участниковChanged();
    #endregion
		
		public Sorevnovaniya()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[ID соревнования]", Storage="_ID_соревнования", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_соревнования
		{
			get
			{
				return this._ID_соревнования;
			}
			set
			{
				if ((this._ID_соревнования != value))
				{
					this.OnID_соревнованияChanging(value);
					this.SendPropertyChanging();
					this._ID_соревнования = value;
					this.SendPropertyChanged("ID_соревнования");
					this.OnID_соревнованияChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Название", DbType="VarChar(50)")]
		public string Название
		{
			get
			{
				return this._Название;
			}
			set
			{
				if ((this._Название != value))
				{
					this.OnНазваниеChanging(value);
					this.SendPropertyChanging();
					this._Название = value;
					this.SendPropertyChanged("Название");
					this.OnНазваниеChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Дата проведения]", Storage="_Дата_проведения", DbType="Date")]
		public System.Nullable<System.DateTime> Дата_проведения
		{
			get
			{
				return this._Дата_проведения;
			}
			set
			{
				if ((this._Дата_проведения != value))
				{
					this.OnДата_проведенияChanging(value);
					this.SendPropertyChanging();
					this._Дата_проведения = value;
					this.SendPropertyChanged("Дата_проведения");
					this.OnДата_проведенияChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Максимальное количество участников]", Storage="_Максимальное_количество_участников", DbType="Int")]
		public System.Nullable<int> Максимальное_количество_участников
		{
			get
			{
				return this._Максимальное_количество_участников;
			}
			set
			{
				if ((this._Максимальное_количество_участников != value))
				{
					this.OnМаксимальное_количество_участниковChanging(value);
					this.SendPropertyChanging();
					this._Максимальное_количество_участников = value;
					this.SendPropertyChanged("Максимальное_количество_участников");
					this.OnМаксимальное_количество_участниковChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
